USE SENAI_HROADS_MANHA;
GO

SELECT * FROM CLASSE;

SELECT * FROM PERSONAGEM;

SELECT * FROM TIPO_HABILIDADE;

SELECT * FROM HABILIDADE;

SELECT * FROM CLASSE_HABILIDADE;

SELECT COUNT (*) AS HABILIDADE FROM PERSONAGEM;

SELECT idHabilidade FROM HABILIDADE;

SELECT nomeHabilidade, nomeTipoHab FROM HABILIDADE
INNER JOIN TIPO_HABILIDADE
ON HABILIDADE.idTipoHab = TIPO_HABILIDADE.idTipoHab;

SELECT nomePersonagem, nomeClasse FROM PERSONAGEM
INNER JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT nomePersonagem, nomeClasse FROM PERSONAGEM
FULL OUTER JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADE
FROM CLASSE 
INNER JOIN CLASSE_HABILIDADE
ON CLASSE.idClasse = CLASSE_HABILIDADE.idClasse
INNER JOIN HABILIDADE
ON HABILIDADE.idHabilidade = CLASSE_HABILIDADE.idHabilidade;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADE
FROM CLASSE 
FULL OUTER JOIN CLASSE_HABILIDADE
ON CLASSE.idClasse = CLASSE_HABILIDADE.idClasse
FULL OUTER JOIN HABILIDADE
ON HABILIDADE.idHabilidade = CLASSE_HABILIDADE.idHabilidade;