USE SENAI_HROADS_MANHA;
GO

SELECT * FROM CLASSES;

SELECT * FROM PERSONAGENS;

SELECT * FROM TIPOS_HABILIDADE;

SELECT * FROM HABILIDADES;

SELECT * FROM CLASSES_HABILIDADE;

SELECT * FROM TIPOS_USUARIO;

SELECT * FROM USUARIOS;

SELECT COUNT (*) AS HABILIDADES FROM PERSONAGENS;

SELECT idHabilidade FROM HABILIDADES;

SELECT nomeHabilidade, nomeTipoHab FROM HABILIDADES
INNER JOIN TIPOS_HABILIDADE
ON HABILIDADES.idTipoHab = TIPOS_HABILIDADE.idTipoHab;

SELECT nomePersonagem, nomeClasse FROM PERSONAGENS
INNER JOIN CLASSES
ON CLASSES.idClasse = PERSONAGENS.idClasse;

SELECT nomePersonagem, nomeClasse FROM PERSONAGENS
RIGHT JOIN CLASSES
ON CLASSES.idClasse = PERSONAGENS.idClasse;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADES
FROM CLASSES
LEFT JOIN CLASSES_HABILIDADE
ON CLASSES.idClasse = CLASSES_HABILIDADE.idClasse
LEFT JOIN HABILIDADES
ON HABILIDADES.idHabilidade = CLASSES_HABILIDADE.idHabilidade;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADES
FROM HABILIDADES
INNER JOIN CLASSES_HABILIDADE
ON HABILIDADES.idHabilidade = CLASSES_HABILIDADE.idHabilidade
INNER JOIN CLASSES
ON CLASSES.idClasse = CLASSES_HABILIDADE.idClasse;

SELECT nomeHabilidade, nomeClasse FROM CLASSES_HABILIDADE
FULL OUTER JOIN CLASSES
ON CLASSES.idClasse = CLASSES_HABILIDADE.idClasse
FULL OUTER JOIN HABILIDADES
ON HABILIDADES.idHabilidade = CLASSES_HABILIDADE.idHabilidade;