CREATE DATABASE SENAI_HROADS_MANHA;
GO

USE SENAI_HROADS_MANHA;
GO

CREATE TABLE CLASSES(
idClasse INT PRIMARY KEY IDENTITY(1,1),
nomeClasse VARCHAR(35) NOT NULL UNIQUE,
);
GO

CREATE TABLE PERSONAGENS(
idPersonagem INT PRIMARY KEY IDENTITY(1,1),
idClasse INT FOREIGN KEY REFERENCES CLASSES(idClasse),
nomePersonagem VARCHAR(50) NOT NULL UNIQUE,
QtndVida TINYINT NOT NULL,
QtndMana TINYINT NOT NULL,
dataAtualizacao DATE NOT NULL,
dataCriacao DATE NOT NULL,
);
GO

CREATE TABLE TIPOS_HABILIDADE(
idTipoHab INT PRIMARY KEY IDENTITY(1,1),
nomeTipoHab VARCHAR(50) NOT NULL UNIQUE,
);
GO

CREATE TABLE HABILIDADES(
idHabilidade INT PRIMARY KEY IDENTITY(1,1),
idTipoHab INT FOREIGN KEY REFERENCES TIPOS_HABILIDADE(idTipoHab),
nomeHabilidade VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE CLASSES_HABILIDADE(
idClasseHab INT PRIMARY KEY IDENTITY(1,1),
idClasse INT FOREIGN KEY REFERENCES CLASSES(idClasse),
idHabilidade INT FOREIGN KEY REFERENCES HABILIDADES(idHabilidade),
);
GO

CREATE TABLE TIPOS_USUARIO(
idTipoUser INT PRIMARY KEY IDENTITY(1,1),
titulo VARCHAR(100) NOT NULL UNIQUE,
);
GO

CREATE TABLE USUARIOS(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idTipoUser INT FOREIGN KEY REFERENCES TIPOS_USUARIO(idTipoUser),
email VARCHAR(100) NOT NULL UNIQUE,
senha CHAR(10) NOT NULL,
);
GO