CREATE DATABASE SENAI_HROADS_MANHA;
GO

USE SENAI_HROADS_MANHA;
GO

CREATE TABLE CLASSE(
idClasse INT PRIMARY KEY IDENTITY(1,1),
nomeClasse VARCHAR(35) NOT NULL UNIQUE,
);
GO

CREATE TABLE PERSONAGEM(
idPersonagem INT PRIMARY KEY IDENTITY(1,1),
idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
nomePersonagem VARCHAR(50) NOT NULL UNIQUE,
QtndVida TINYINT NOT NULL,
QtndMana TINYINT NOT NULL,
dataAtualizacao DATE NOT NULL,
dataCriacao DATE NOT NULL,
);
GO

CREATE TABLE TIPO_HABILIDADE(
idTipoHab INT PRIMARY KEY IDENTITY(1,1),
nomeTipoHab VARCHAR(50) NOT NULL UNIQUE,
);
GO

CREATE TABLE HABILIDADE(
idHabilidade INT PRIMARY KEY IDENTITY(1,1),
idTipoHab INT FOREIGN KEY REFERENCES TIPO_HABILIDADE(idTipoHab),
nomeHabilidade VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE CLASSE_HABILIDADE(
idClasseHab INT PRIMARY KEY IDENTITY(1,1),
idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
idHabilidade INT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
);
GO

CREATE TABLE TIPO_USUARIO(
idTipoUser INT PRIMARY KEY IDENTITY(1,1),
titulo VARCHAR(100) NOT NULL UNIQUE,
);
GO

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idTipoUser INT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUser),
email VARCHAR(100) NOT NULL UNIQUE,
senha CHAR(10) NOT NULL,
);
GO