USE SENAI_HROADS_MANHA;
GO

SELECT * FROM CLASSE;

SELECT * FROM PERSONAGEM;

SELECT * FROM TIPO_HABILIDADE;

SELECT * FROM HABILIDADE;

SELECT * FROM CLASSE_HABILIDADE;

SELECT * FROM TIPO_USUARIO;

SELECT * FROM USUARIO;

SELECT COUNT (*) AS HABILIDADE FROM PERSONAGEM;

SELECT idHabilidade FROM HABILIDADE;

SELECT nomeHabilidade, nomeTipoHab FROM HABILIDADE
INNER JOIN TIPO_HABILIDADE
ON HABILIDADE.idTipoHab = TIPO_HABILIDADE.idTipoHab;

SELECT nomePersonagem, nomeClasse FROM PERSONAGEM
INNER JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT nomePersonagem, nomeClasse FROM PERSONAGEM
RIGHT JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADE
FROM CLASSE 
LEFT JOIN CLASSE_HABILIDADE
ON CLASSE.idClasse = CLASSE_HABILIDADE.idClasse
LEFT JOIN HABILIDADE
ON HABILIDADE.idHabilidade = CLASSE_HABILIDADE.idHabilidade;

SELECT nomeClasse AS CLASSE, nomeHabilidade AS HABILIDADE
FROM HABILIDADE 
INNER JOIN CLASSE_HABILIDADE
ON HABILIDADE.idHabilidade = CLASSE_HABILIDADE.idHabilidade
INNER JOIN CLASSE
ON CLASSE.idClasse = CLASSE_HABILIDADE.idClasse;

SELECT nomeHabilidade, nomeClasse FROM CLASSE_HABILIDADE
FULL OUTER JOIN CLASSE
ON CLASSE.idClasse = CLASSE_HABILIDADE.idClasse
FULL OUTER JOIN HABILIDADE
ON HABILIDADE.idHabilidade = CLASSE_HABILIDADE.idHabilidade;